In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
url="https://www.bookchor.com"
r= requests.get(url)
print(r)
#product-item

url="https://www.bookchor.com/category/15/99-store"
r= requests.get(url)
print(r)

soup=BeautifulSoup(r.text, "lxml")

<Response [200]>
<Response [200]>

In [4]:
Price=[]
price=soup.find_all("div", class_="pi-price")
for i in price:
    price=i.text
    Price.append(price)
#print(Price)

In [5]:
Price1=[]
for j in Price:
    k=j.split(".")
    #print(k[1])
    Price1.append(k[1])
print(Price1)
print(len(Price1))

[' 59', ' 99', ' 59', ' 59', ' 64', ' 59', ' 88', ' 59', ' 59', ' 59', ' 36', ' 49', ' 49', ' 55', ' 55', ' 55', ' 55', ' 55', ' 55', ' 55', ' 55', ' 59', ' 59', ' 59', ' 59', ' 59', ' 59', ' 59', ' 59']
29

In [7]:
import re
Author=[]
author=soup.find_all("p",string=re.compile("By"))
for i in author:
    author=i.text
    Author.append(author)

In [8]:
Author1=[]
Author2=[]
for j in Author:
    h=j.split(":")
    #print(h[1])
    Author1.append(h[1])
#print(Author1)    
for l in Author1:
    A=l.replace("...", "")
    #print(A)
    Author2.append(A)
print(Author2)
print(len(Author2))

[' James Patterson', ' Lisa Gardner', ' Jennifer Weiner', ' Wendy Holden', ' Mark Walden', ' Charlaine Harris', ' Holly Smale', ' Susan Lewis', ' Lionel Shriver', ' Jennifer Donnelly', ' NCERT', ' Shani Greene-Dowdell', ' Good Housekeeping In', ' Annie Groves', ' Sue Townsend', ' Peter Kay', ' Sophie Kinella', ' Stephenson, Pamela', ' Nick Hornby', ' Elaine Everest', ' John Diamond', ' Janet Evanovich', ' Joan Jonker', ' Katie Flynn', ' Janet Evanovich', ' Robert Muchamore', ' Robert Harris', ' Parsons, Tony', ' Joanna Trollope']
29

In [9]:
Name=[]
Name1=[]
for i in soup.find_all("h3"):
    n=i.text
    Name.append(n)
#print(Name)    

for l in Name:
    A=l.replace("...", "")
    #print(A)
    Name1.append(A)
    if 'More Books' in Name1:
        Name1.remove('More Books')
    
print(Name1)
print(len(Name1))

['Sail', 'Hide', 'In Her Shoes', 'Beautiful People', 'The Spooks Tale Inte', 'All Together Dead', 'Geek Drama', 'Missing', 'Post-birthday World', 'Gathering Light', 'Vasant Bhaag 2 Textb', 'chauds les glacons', 'Great Escapes', 'Child of the Mersey', 'Adrian Mole from Min', 'Sound of Laughter', 'Shopaholic And Baby', 'Billy Connolly', 'High Fidelity', 'The Butlins Girls', 'Snake Oil', 'Notorious Nineteen: ', 'Home is Where the He', 'Cuckoo Child', 'Takedown Twenty', 'Eagle Day: Book 2 (H', 'Enigma', 'Man and Wife', 'Second Honeymoon']
29

In [10]:
import pandas as pd
data={
    'Name':Name1,
    'Price':Price1,
    'Author':Author2
}

In [11]:
df=pd.DataFrame(data)

In [12]:
df

                    Name Price                 Author
0                   Sail    59        James Patterson
1                   Hide    99           Lisa Gardner
2           In Her Shoes    59        Jennifer Weiner
3       Beautiful People    59           Wendy Holden
4   The Spooks Tale Inte    64            Mark Walden
5      All Together Dead    59       Charlaine Harris
6             Geek Drama    88            Holly Smale
7                Missing    59            Susan Lewis
8    Post-birthday World    59         Lionel Shriver
9        Gathering Light    59      Jennifer Donnelly
10  Vasant Bhaag 2 Textb    36                  NCERT
11    chauds les glacons    49   Shani Greene-Dowdell
12         Great Escapes    49   Good Housekeeping In
13   Child of the Mersey    55           Annie Groves
14  Adrian Mole from Min    55           Sue Townsend
15     Sound of Laughter    55              Peter Kay
16   Shopaholic And Baby    55         Sophie Kinella
17        Billy Connolly    55     Stephenson, Pamela
18         High Fidelity    55            Nick Hornby
19     The Butlins Girls    55         Elaine Everest
20             Snake Oil    55           John Diamond
21  Notorious Nineteen:     59        Janet Evanovich
22  Home is Where the He    59            Joan Jonker
23          Cuckoo Child    59            Katie Flynn
24       Takedown Twenty    59        Janet Evanovich
25  Eagle Day: Book 2 (H    59       Robert Muchamore
26                Enigma    59          Robert Harris
27          Man and Wife    59          Parsons, Tony
28      Second Honeymoon    59        Joanna Trollope

In [14]:
the_list=df.values.tolist()
import csv
with open('bookchor.csv', 'w', newline='') as file:
     writer = csv.writer(file)
     writer.writerows(the_list)